### ISSUE TITLE
are this EFI have problem with Bluetooth?

### ISSUE THREAD

**Issue by irfanhutomo2** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#1]
i try EFI from [sambow23](https://github.com/sambow23/Dell-XPS-13-7390-macOS/commits?author=sambow23) and [ericfjosne](https://github.com/ericfjosne/Dell-XPS-7390-Opencore/commits?author=ericfjosne), have problem when bluetooth sometimes goes off and cannot turn on, only restart can fix

and are combojack works?

**Comment by irfanhutomo2** [comment]
and are combojack works?

**Comment by H3C4T0M8** [comment]
Sorry for waiting. I don't think that the Efi have problems with Bluetooth . I will check this and upload the fixed Efi in the next days. At moment the keyboard have issue after wakeup, but I know how to fix

**Comment by irfanhutomo2** [comment]
thanks youuu !!! waiting for stable build

**Comment by H3C4T0M8** [comment]
Check it...I have finish it now. thanks for waiting
i don't know how to do with combo jack. do you know how to use it?

**Comment by irfanhutomo2** [comment]
hey i will try it now, still downloading the montrey update. i will report later

**Comment by irfanhutomo2** [comment]
i want use monterey what version should i use?

**Comment by H3C4T0M8** [comment]
Sure, you can try Monterey if you like

**Comment by H3C4T0M8** [comment]
Alternativ you can test this efi.... https://mega.nz/file/wpcghKIY#JMnycrgQWwPClCmCJF6mxecTkU7bonhsAzMaMPO2xt8

**Comment by H3C4T0M8** [comment]
Little update: after a bit of searching on the internet, it seems to give problems with the bluetooth kexten on some intel models in general. under big sur even more than under montery. So it's a good idea to test everything... Big Sur, Monterey... old kext releases as well as the new releases
