### ISSUE TITLE
No Wi-Fi or Bluetooth Support

### ISSUE THREAD

**Issue by Qunqun64** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#10]
Hello all,
Thank you for your work!!

I come from another older repository where I had the same issue, but with Monterey. (https://github.com/sambow23/Dell-XPS-13-7390-macOS)
I tried to use theses EFI on my XPS and had no problems during installation (exept for deutsch 😄 ) - it's great!
Unfortunately, I cannot get Bluetooth and WiFi support to work. Perhaps my configuration is different, but could it be enough to cause these issues? I am running MacOS Ventura and I tried both the EFI in OC0.8.6 and the EFI in OldEFI/OC0.8.2ventura.
Did I miss any step maybe ? Do you have any suggestions?

Thank you in advance for your help, and I look forward to hearing your suggestions!

**Comment by H3C4T0M8** [comment]
At moment I am in Ukraine. Wife and Bluetooth will work... I will help you on Thursday, when you don't fix it till this day.

Thanks

**Comment by Qunqun64** [comment]
Thanks for your reply, I'll try to wait and fix it :)
have a nice week!!

**Comment by H3C4T0M8** [comment]
Thanks 👍

**Comment by irfanhutomo2** [comment]
hey @Qunqun64 tried install bigsur i have same problem like you in monterey and ventura

**Comment by H3C4T0M8** [comment]
You need for each macOS the wife kext for this version. I am on the way back to Poland and Germany. Thursday I have time

**Comment by Qunqun64** [comment]
Hey :)
I've tried to fix that with different releases of WiFi and Bluetooth kexts, but nothing good happened, even worse!
So do you have news on your side?
Thanks in advance!

**Comment by irfanhutomo2** [comment]
try this: @Qunqun64 
wifi: https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0-alpha/AirportItlwm-Ventura-v2.2.0-DEBUG-alpha-ddd2768.zip
BT: https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/download/v2.2.0/IntelBluetooth-v2.2.0.zip & 
https://github.com/acidanthera/BrcmPatchRAM/releases/download/2.6.5/BrcmPatchRAM-2.6.5-RELEASE.zip (only need **BlueToolFixup**)

plus: maybe you need delete itlwm: CatAirportItlwm.kext, MonAirportItlwm.kext & BigAirportItlwm.kext

and then update your config after that ,guide : 
1. download propertree
2. open 
3. choose your config.plist
4. then snapshot from your EFI/OC
5. Save

maybe thats helps!

**Comment by Qunqun64** [comment]
Thanks for your suggestion @irfanhutomo2 !
Unfortunately it doesn't works, always this sad icon searching for networks without success... (the card is recognized it's the worse thing, we are so close!!)
I'll continue to investigate.

**Comment by H3C4T0M8** [comment]
Sorry for late answer. I don't got much time in the last days.
What macOS you use?

Ah I see... Ventura. Let me check

**Comment by Qunqun64** [comment]
I tried both the latest release of Ventura with your latest EFI folder (oc0.8.2ventura and oc0.8.6) and latest release of Monterey with your commit https://github.com/H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore/commit/a3939cc5331365a5077ffd7c7305acd7113f93da ... But both failed. (Many others combinations too)
Thank you for your help!!

**Comment by H3C4T0M8** [comment]
At moment Bluetooth don't work Ventura here too. Maybe with older kext, or after new Restart. But I think with Ventura at moment too much problems because CPU usage. 
I send you my EFI in some minutes... need to test something. If it work, better to copy and past the kexts and settings, because I don't finished the EFI and looks more like kaos at moment

**Comment by H3C4T0M8** [comment]
or wait...I will send you all kexts. my cpu sucks too much on Ventura with this efi. 
[kexts.zip](https://github.com/H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore/files/11357523/kexts.zip)

**Comment by Qunqun64** [comment]
Thank you for all of that!
I have to go to sleep, but I'll try again tomorrow. If it doesn't work, it's not too bad, I'll roll back to Monterey, which is more stable, I suppose

**Comment by Qunqun64** [comment]
Bad news... it doesn't work better with these kexts. Do we have the same hardware? I have a XPS 7390 with an i7 10510U, Intel UHD Graphics, 16GB RAM, NVMe updated to Micron 3400 2TB, and Intel AX1650 for Wi-Fi and Bluetooth. My version of Ventura is 13.3.1, and I am using OC 0.8.6.
I understand that I may not have the technical skills for this kind of thing. To make sure everything is done correctly, I am using the official command from Apple to create a bootable USB key. Then, I copy the EFI folder to the EFI partition of the key, and it is ready for installation. After installation, I simply put the same EFI folder on the EFI partition of my NVMe. If I want to change the kexts in my EFI, I follow the guide from irfanhutomo2 above.
Is that okay? I just want to be sure I'm not taking any shortcuts and that I won't forget anything.
Thanks for your help anyway, hope we'll find a solution! :)

**Comment by H3C4T0M8** [comment]
I think I gave the same wifi model, but not sure. Give you in one or two hours more infos. Normally it will be show as a AX200 in macOS. 

![image](https://user-images.githubusercontent.com/96039915/235366308-cd0fb800-c713-4a6d-9fe0-552234952dca.png)

**Comment by H3C4T0M8** [comment]
Windows say this Modul I have![image](https://user-images.githubusercontent.com/96039915/235378462-a992ccf5-0662-47d2-b974-eab7cc6d8255.jpeg)

**Comment by H3C4T0M8** [comment]
we try a other way. I will add an other kext. but you need to install something in macOS. 
read here...I think your card work normally too[
](https://github.com/OpenIntelWireless/itlwm/issues/823)

**Comment by H3C4T0M8** [comment]
Take this EFI Folder and install the Heliport app, that inside the packet. hope it fix the problem !!!

https://files.fm/u/xbn77cajw

**Comment by irfanhutomo2** [comment]
hey @H3C4T0M8 sorry for OOT, are you can update this EFI to lastest OC & with vodooHDA?

**Comment by H3C4T0M8** [comment]
Good morning. I just stand up from bed. The voodoo kext inside the EFI, or not? You only need to activate it. I will check later, because I don't remember what I have upload exactly 🤣 give me 1-2 hours... thanks

**Comment by Qunqun64** [comment]
Well, I am definitely the worst hackintosher and the worst geek on this entire planet: trying to check the model of my network card, I reinstalled Windows, and then I realized that the Wi-Fi was not working either.

It turns out that the keyboard button (equivalent to F13) that turns off Wi-Fi is actually a physical switch that disables the entire card, instead of just being a software shortcut that would disable Wi-Fi in the OS...

I am extremely disappointed to have wasted so much time on this completely stupid mistake. The different EFI's are working, so I am currently trying to optimize everything because it's still unstable.

Thank you for your help!! I will keep you updated on my progress :)

**Comment by H3C4T0M8** [comment]
No problem... have fun with your Hackintosh. But what you mean with unstable?

@irfanhutomo2  today I don't found the time. Will do it tomorrow

**Comment by Qunqun64** [comment]
Unstable because, about half the time, the WiFi is inaccessible after a restart. Sometimes it tells me that it's connected, but the internet doesn't work (no ping at all, so I suppose my interface isn't configured, I don't know I'll see what I can do). And quite often, Bluetooth devices are not detected (my JBL speaker is connected, my Sony headphones are impossible to detect, my phone is okay, my other computer is impossible... It's random).

I'll try several combinations and let you know which one works best. But tomorrow 😄

**Comment by H3C4T0M8** [comment]
The Bluetooth problem, that some devices can't connect is a Intel Bluetooth device problem. Some devices not work, I don't know if you can fix it ( you can try the EFI that I upload here to test, because I'm this EFI is a new kext for Bluetooth inside the EFI configuration... I never test this kext byself, so maybe it will fix this problem )
Because your WiFi problem. 
In this EFI I upload here, this kext work for each macOS, but need a app to connect to wifi network. When you use a EFI with the other kext, you need for each macOS a separate other WiFi kext version, to get the best result. 
With macOS Catalina (100%) it will connect directly, and I think with Big Sur the same. At Monterey and Ventura they have change something, and there this problems with Intel WIFI Moduls have start.
You can test to fix it with the way, to delete the WiFi configuration in network options and try a new boot from laptop.

At last it is good to know what EFI and macOS you use, that I can check if you really use a EFI with best kexts. Thanks

ps: if you like to test different macOS, you can install and boot the macOS all in separate containers on your ssd of your laptop. I have all macOS on my Dell, and can select the macOS I like to boot at start in OpenCore boot menu.

**Comment by H3C4T0M8** [comment]
NEW EFI to TEST (AppleALC.kext , so Voodoo kext not longer needed )

https://files.fm/u/f2a3tb2ee

**Comment by Qunqun64** [comment]
Hello everyone :) Here's some feedback after a week of testing different EFIs!
- I specifically tested the EFI from the repository, with OC 0.8.2. It works well and is very stable! However, when it comes to Wi-Fi, a restart prevents any connection and the card seems to be blocked. Only a complete shutdown of the PC will reactivate it. In addition, hybrid sleep does not work and causes the PC to crash and restart, which makes it impossible to use the network card. I also noticed a surprising problem: when I connect my monitor via USB, only resolutions up to 2560x1440 are supported. In this case, since my monitor is 3440x1440, I cannot use it at full resolution.
- I also tested the same EFI with the modifications suggested by irfanhutomo2, but the results are strictly identical, with unfortunately a much longer boot time (3 minutes vs 25 seconds with the previous EFI).
- Finally, I tested the EFI that uses Heliport. I'm not a fan of using an additional tool, especially since it has the same problems upon restart. However, my monitor is at full resolution with this EFI!! The biggest downside is that sound doesn't work with this version... I haven't tried installing AppleALC299, maybe that would fix the problem? I don't know.

And this morning, I saw this message offering a brand new EFI!! Fantastic!! Thank you very much!!
I'm testing it now, and it seems that the result is very similar to the first EFI from the repository, so unfortunately not much improvement. ~~And my monitor is still stuck at a low resolution.~~ Edit: After some time in sleep mode, I opened my computer and was surprised to see that my secondary screen turned on, in full resolution this time!!! I have absolutely no explanation to give, I don't understand what happened.

I'm following the OpenCore guide to upgrade to OC 0.9.1, but it's taking a long time! I'm not at all sure I'll be able to produce a stable EFI, but I'll keep you posted!
Thanks in any case for your support and ideas, it's great :)
Have a good day!!

**Comment by H3C4T0M8** [comment]
Take this files, and change the layout id to 24
[trial_ID24_only_Speaker_HP_and_Mic.zip](https://github.com/H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore/files/11426988/trial_ID24_only_Speaker_HP_and_Mic.zip)

**Comment by Qunqun64** [comment]
Hello everyone,
Thank you for your suggestion H3C4T0M8. I ultimately didn't need to use it as I no longer had any issues with the sound in my recent attempts.

I tried Dortania's tutorial to create my own EFI, with the help of the kexts provided here, and it went relatively well! However, I still lack stability.
Due to time constraints, I went back to the latest version you shared here, which has proven to be much more stable than the previous ones. So, I'll stay with OC v0.9.2, which satisfies me!

I'll mark the topic as resolved, as it has been for a while now. Thank you again for your valuable assistance and support!

Happy hackintoshing to all! :)

**Comment by H3C4T0M8** [comment]
Hey... nice to read this. Can you check the temperature of your system and CPU Usage in the next days, and can you post all here? 
Have a nice day !!! Thanks

**Comment by Qunqun64** [comment]
Hey @H3C4T0M8, my observations on the temperatures this week:

- When my device is idle, it stays at around 40°C. It's a bit warmer compared to the Windows version, but nothing major to worry about.
- During regular tasks like browsing the internet, using Word, or watching videos, the temperature ranges from 40 to 55°C. It can vary depending on what I'm doing, like clicking or scrolling, but overall, it's quite reasonable.
- Whether I'm using it on battery or plugged into the power source, the temperatures stay the same. The fan rarely kicks in during these situations, which is great.
- Now, during charging, things get a bit hotter. For some reason, it easily reaches 70°C, and that's when the fans start spinning. But once it's fully charged, it goes back to normal.
- Finally, during demanding tasks like running tests, editing videos, or using virtual machines, the processor goes up to 100°C consistently. It goes through phases of 4GHz at 100°C and 1.5GHz at 70°C.

Overall, the temperatures are quite reasonable and satisfactory. The battery life is slightly shorter compared to Windows, but it's not a significant decrease. So, I'm happy with it!

**Comment by H3C4T0M8** [comment]
Hey.

The Problem with the temperature ( that what you say ) can you fix with a other CPU Power Management... I never have try to find the best settings in Power Management , because the problem with AppleALC and heat issue.

you can build the frequency kext with this ways:
https://github.com/corpnewt/CPUFriendFriend

https://github.com/stevezhengshiqi/one-key-cpufriend

At moment I try to fix a Ventura Display Backlight issue (1-2 minutes black display at boot, and then it change to normal ) or when I go into sleep, and wakeup again. the display normal.

You can test the settings what you think the best for you

here some infos to make the cpu power management

https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#enabling-x86platformplugin)


PS: What SMbios you use?

**Comment by Qunqun64** [comment]
I use SMBIOS for MacBookAir9,1 (shown as MacBookAir retina 13" 2020), I don't know if it's the best choice, MacBookPro15,2 seems to be good too, but I didn't noticed improve or deteriorations of perfs with it.

**Comment by H3C4T0M8** [comment]
I think I have fix the CPU Issue.
![Bildschirmfoto 2023-06-05 um 18 39 34](https://github.com/H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore/assets/96039915/5f9baee7-bb7a-4ca7-b466-711205a45689)

https://files.fm/u/4z3yu7a99

Bluetooth fixed in the last Ventura Beta version, so don't downgrade Bluetooth and Bluetooth relevant kexts !!! Smbios is now 16,2...
