### ISSUE TITLE
are bluetooth is stable?

### ISSUE THREAD

**Issue by restufff** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#2]
when I'm using sammbow23 build Bluetooth always crashes after long use and only solved by restart.

**Comment by H3C4T0M8** [comment]
hi. I don't have this problem after wakeup. but I need to check the last refi build, because a user have tell me a big issue with crash. tonight I look for the problem and change all ssdt´s to minimum. I will text you when I fix it

**Comment by H3C4T0M8** [comment]
Its stable now. thanks for waiting

**Comment by H3C4T0M8** [comment]
Alternativ you can test this efi.... https://mega.nz/file/wpcghKIY#JMnycrgQWwPClCmCJF6mxecTkU7bonhsAzMaMPO2xt8

after a bit of searching on the internet, it seems to give problems with the bluetooth kexten on some intel models in general. under big sur even more than under montery. So it's a good idea to test everything... Big Sur, Monterey... old kext releases as well as the new releases
