### ISSUE TITLE
can we use for ventura ?

### ISSUE THREAD

**Issue by irfanhutomo2** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#3]
can inuse this for ventura beta?

**Comment by H3C4T0M8** [comment]
I don't know if it work.i think first it need a update to oc0.8.2 dev version. Need to check it in the next days

**Comment by irfanhutomo2** [comment]
thanks mate, i tried update to monterey but back to big sur again because bluetooth unstable, maybe in ventura bt can be more stable?

**Comment by H3C4T0M8** [comment]
I have read the Bluetooth problems not in all smbios. MacBook Pro 15,1 + 15,2 I think fine. The programmer have speak about it. 
It's really strange....i have problems in big Sur, in Monterey all good 🤣
Maybe I will upload a new efi later. I check to install Ventura at moment.

Yes. It can be more stable. You need to test smbios and maybe other Bluetooth kext.

**Comment by irfanhutomo2** [comment]
owh thanks i will try it again in ventura thanks for your works!!

**Comment by H3C4T0M8** [comment]
I upload the efi in the next 60 minutes. Installation finished

**Comment by irfanhutomo2** [comment]
are everythings works?

**Comment by H3C4T0M8** [comment]
No... Not at moment. At moment my config file damaged after each savings. I need to test Bluetooth ( it don't have work, but I'm sure it is because I have Bluetooth for 4 macos in one efi. Need to test what Bluetooth kext need for Ventura and need to add the kernel numbers again.

And need to test if installation work without some settings, because I don't like it. Secure boot ...

I think I will make the efi tomorrow finish. When you like the efi to test I can send you the unfinished efi

**Comment by irfanhutomo2** [comment]
thankss maybe im waiting the finish efi

**Comment by H3C4T0M8** [comment]
Ok. At moment no wlan and no Bluetooth 🤒 hope I find a way to fix it.

Thanks for waiting 🙌

**Comment by irfanhutomo2** [comment]
alpha itlwm just release but not fow intelbluetooth, thanks for always replying mee

**Comment by H3C4T0M8** [comment]
Sure...i answer directly when I have the time. Hope they will release new kexts. Airport have release a Ventura kext, but it don't work. I will check it in the next days again

**Comment by H3C4T0M8** [comment]
I will update with working Bluetooth and wlan soon... It work now.

**Comment by H3C4T0M8** [comment]
Iran you check the refi....if all work? THX

**Comment by irfanhutomo2** [comment]
thankss i will try it, downloading ventura now, any suggestion for update from bigsur? 
any different from installing monterey or bigsur?

**Comment by H3C4T0M8** [comment]
You can install from other os to new partition, or boot installer directly

**Comment by irfanhutomo2** [comment]
i wanna try using update from bigsur , it's that okay?

**Comment by H3C4T0M8** [comment]
Think so. But take care... it's better to make a backup or try to install to separat partition.

**Comment by H3C4T0M8** [comment]
You have test the efi? Did you got problems, or all work?

**Comment by irfanhutomo2** [comment]
not yet, always faild update from system. i try find a better connection mine is trash

**Comment by irfanhutomo2** [comment]
already tested, working great but i found

1. if i update Apple ALC to newer kext, no sound
2. BT cannot connect to old BT mouse (Logi Pebble)
3. cannot use macro key on mouse ( maybe ventura bug)
4.


can we disable this?
![image](https://user-images.githubusercontent.com/97343498/175660663-6c488e5a-d906-4e0b-bad6-0a81cdbd95da.png)
if i accidentally clil power off then the system is hang only restart can solve

**Comment by H3C4T0M8** [comment]
Yes. You need to use the applealc from my efi, because it's a unsigned layout.

Can you test the 3 Bluetooth kexts from old efi... Maybe than Bluetooth work again 😉

I need to ask how I can fix the problem from picture. I got this problem already on my msi z490 , but I don't remember how I have fix this. Give me some days

**Comment by irfanhutomo2** [comment]
old efi is efi from monterey? and i think we dont need IntelBluetoothInjector after monterey right? only BlueToolFixup and IntelBluetoothFirmware needed

thanks i appreciate thatt!!

**Comment by H3C4T0M8** [comment]
Yes the inject kext not need...i have deactivate it in config with kernel version setting for Monterey and Ventura

**Comment by irfanhutomo2** [comment]
`Can you test the 3 Bluetooth kexts from old efi... Maybe than Bluetooth work again 😉`

is that bt kext from monterey or what?

for issue from my picture i found to remove it, hold command button and drag the icon out from menu bar

**Comment by H3C4T0M8** [comment]
The Bluetooth kext versions don't have spatial kext versions for each MacOS. But I don't remember what version I have use in the last efi. I have change the kexts for you, because I don't got problems. ( you need to test out what kext release the best option for you)
Sometimes the last version work good, sometimes the version before the final version work better.

Oh, thanks for the info because Thunderbolt option...i will test it later 😅

**Comment by irfanhutomo2** [comment]
oh then i try download 2.0.0 intelBT right?

**Comment by H3C4T0M8** [comment]
Right

**Comment by irfanhutomo2** [comment]
still don't work and i back to big sur, don't know why in monterey BT crash but in ventura works but old mouse BT cannot connect

**Comment by H3C4T0M8** [comment]
oh. I really like the XPS laptop...but the onboard intel model really shit :-( we can be happy that peoples have make a kext for macOS, but it don't work really fine.

you already have change the smbios? what smbios you use at moment?

**Comment by irfanhutomo2** [comment]
i love xps too thanks for making kext for this laptop,

i use MacBookPro15,2

**Comment by H3C4T0M8** [comment]
Bluetooth and wlan work now with Ventura

**Comment by irfanhutomo2** [comment]
thanksss!! i using your kext in bigsur now, maybe when ventura is release i will use ventura again.
can you update OC to 0.8.2 for bigsur?

**Comment by H3C4T0M8** [comment]
I send you later a link to new OC efi

**Comment by irfanhutomo2** [comment]
thanksss!!!

**Comment by H3C4T0M8** [comment]
What efi u use exactly?

**Comment by irfanhutomo2** [comment]
now [OpenCore 0.8.0](https://github.com/H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore/tree/main/OpenCore%200.8.0) , in big sur

**Comment by H3C4T0M8** [comment]
Ok. I need to drive to post office now, than I will do a update.
If you don't know how to do byself, you can check this tool. With this you can update efi folders with only some mouseclicks. But don't forget to unselect the kext that don't work after update.

Here the link: https://github.com/ic005k/OCAuxiliaryTools

**Comment by irfanhutomo2** [comment]
don't know why always detect 0.7.8 
![image](https://user-images.githubusercontent.com/97343498/181472260-d3f696c9-4fd4-4e05-bca8-a768f2fc8210.png)

**Comment by H3C4T0M8** [comment]
You need first to do update of database. I will text you all step by step soon

**Comment by H3C4T0M8** [comment]
I will make the update now + upload a other efi for this system. The other efi I test at moment byself

here are a link for update to oc 0.8.3. please use your smbios! (not all kexts updated , so you can't boot Ventura with this efi at momemt !!! https://files.fm/f/pf2rucwr3

**Comment by irfanhutomo2** [comment]
thanksss!!!

**Comment by H3C4T0M8** [comment]
I will send you a new efi for testing soon. Yesterday I got a new audio layout kext. Tomorrow I will test all layouts in Ventura

**Comment by irfanhutomo2** [comment]
thanks mann your are the bestt!!

are jack audio works ?
