### ISSUE TITLE
Headset is not working ?

### ISSUE THREAD

**Issue by wdubaiyu** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#4]
Headset is not working ?

**Comment by H3C4T0M8** [comment]
Hello. You can try/test layout 22 , 23, or 24. But I think the headset won't work without codecommander.

Maybe the guys at www.osxlatitude.com forum can help you. 🤷‍♂️

I never have look for codecommander way

I will change the infos from my upload soon... For me it was relevant to get sound in MacOS Ventura

**Comment by H3C4T0M8** [comment]
https://github.com/black-dragon74/ALCPlugFix-Swift or try to use this...at moment I can't test

**Comment by irfanhutomo2** [comment]
i tried download but dont know how to use it

**Comment by irfanhutomo2** [comment]
i found this on onternet are worth trying? https://github.com/hackintosh-stuff/ComboJack

**Comment by H3C4T0M8** [comment]
i don't know. but you can ask this guy from osx forum https://osxlatitude.com/forums/topic/11316-how-to-fix-static-noisedistortioncrackling-sound-and-combo-jack-on-laptops

and check this page https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13 I know its old, but maybe it work too. you can ask there

**Comment by irfanhutomo2** [comment]
okay will try it later, im bad using scripting tutorial

**Comment by irfanhutomo2** [comment]
https://github.com/leon0410898/XPS13-9300-hackintosh/tree/master/ComboJack_Installer

are this help?

**Comment by irfanhutomo2** [comment]
https://elitemacx86.com/threads/audio-distortion-when-using-headphones-on-laptops-clover-opencore.185/

jack audio fix

**Comment by H3C4T0M8** [comment]
It work?

**Comment by irfanhutomo2** [comment]
i tried, but not know how to doing this `For OpenCore:
If you're using OpenCore, copy the kext to EFI/OC/Kexts. You'll also need to add the kext entry in Kernel section of your config.plist.`

sorry for late reply

**Comment by taida2203** [comment]
seem like none of above solution work. @H3C4T0M8 do you have any advice on this ?

**Comment by taida2203** [comment]
@irfanhutomo2  is this solution work on your side ? https://elitemacx86.com/threads/audio-distortion-when-using-headphones-on-laptops-clover-opencore.185/

**Comment by H3C4T0M8** [comment]
Hi. Sorry for my late answer. In the last weeks I don't have work much with my Dell XPS laptop, because I have buy a MacBook Air M2. 

I think this will work, but never have try it byself. When you need help, then try to ask at the thread from your link, or ask at  [www.osxlatitude.com](https://osxlatitude.com) Forum. The mods there have much knowledge, and when I remember right, Jake lo https://osxlatitude.com/profile/1549-jake-lo/ know what you need to do.

**Comment by irfanhutomo2** [comment]
maybe this is work https://github.com/black-dragon74/ALCPlugFix-Swift/releases/

**Comment by H3C4T0M8** [comment]
i will close this thread.
