### ISSUE TITLE
kernel panic resuming from sleep.

### ISSUE THREAD

**Issue by deonthomasgy** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#5]
Hi,
I am using a Dell XPS 13 7390 - i5 model. everything seems to be working fine using your 0.8.4 EFI files, however resuming from sleep does not work, the computer simply reboots. Do you know what might be the cause?

Bios version 1.17.0

**Comment by H3C4T0M8** [comment]
What cpu i5 exactly? And what macOS you use?

So you use the last efi upload from me... right?

**Comment by deonthomasgy** [comment]
Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz | I upgraded my Big Sur to Monterey (not fresh install).

Yes, Latest EFI from you without any changes. I am currently testing your Opencore 8.0 EFI

**Comment by deonthomasgy** [comment]
Additionally, this laptop came with a Samsung P991, I replaced it with "SK hynix SC300 M.2 2280 128GB"

**Comment by H3C4T0M8** [comment]
Ok. I will check it later... and will think about it. 
Let me know if you get this problem with other efis too. I have change much at the Ventura efi.... so maybe you got this problem only with last efi.

But please check if cpu powermanagment kext and ssdt deactivate.... this is only for i7 10510u cpu

**Comment by deonthomasgy** [comment]
Ok, thank you very much for your speedy reply, I will run EFI 8.0 for awhile to see if I run into any issues. 

Once again, thank you.

**Comment by H3C4T0M8** [comment]
You welcome. I'm sure we will fix this issue. 
At moment I clean my rooms, so I will check later

**Comment by H3C4T0M8** [comment]
I have check the efi fast. You can test the 0.8.4 without VoodooTSCSync.kext... so please deactivate for Testing

I think this kext make the Panik

Alternative you can deactivate Thunderbolt ssdt too

**Comment by deonthomasgy** [comment]
> You welcome. I'm sure we will fix this issue. At moment I clean my rooms, so I will check later

Sunday's work.

**Comment by deonthomasgy** [comment]
> I have check the efi fast. You can test the 0.8.4 without VoodooTSCSync.kext... so please deactivate for Testing
> 
> I think this kext make the Panik
> 
> Alternative you can deactivate Thunderbolt ssdt too

Thank you, I will try this out, i'm still on EFI 8.0 and i've closed the lid a few times and it resumed properly. I will continue to test for a few more days before, moving back to 8.4

I really appreciate you taking the time to look into this, thank you.

**Comment by deonthomasgy** [comment]
Do you have a discord/irc channel for this kind of support?

**Comment by H3C4T0M8** [comment]
My Discord name : Hecatomb#5073

**Comment by irfanhutomo2** [comment]
im using 8.4 on monterey got kernel panic from sleep

**Comment by deonthomasgy** [comment]
HI @irfanhutomo2, Try EFI 8.0 folder, it seems to panic less. Can you share the specs of your laptop.

**Comment by irfanhutomo2** [comment]
im using i5-10210U and 8gb ram

**Comment by deonthomasgy** [comment]
same here, i'm having random reboot issues. How does EFI 8.0 folder work for you @irfanhutomo2 ?

**Comment by irfanhutomo2** [comment]
currently i still use 8.4 on big sur because i think its more stable and block s3 sleep on bios

**Comment by deonthomasgy** [comment]
Ok, I'm thinking of this too, I've blocked s3 sleep because even in Linux it has the same issue. How do you manage closelid? Does big sur go straight to hibernation?

**Comment by deonthomasgy** [comment]
@irfanhutomo2 how's it working for you with s3 sleep blocked?

**Comment by irfanhutomo2** [comment]
close lid dont make laptop go to hibernate, and still awake because s3 sleep blocked, and im okay without sleep

**Comment by irfanhutomo2** [comment]
this some Explanation https://github.com/zspherez/Dell-XPS-9500-4K-UHD-Monterey#s3-sleep-issue-with-xps-9500-and-other-modern-laptops---credit-to-zachs78

**Comment by deonthomasgy** [comment]
@irfanhutomo2 , this might help with closelid hibernate.
https://www.reddit.com/r/hackintosh/comments/dtuifz/fix_sleep_by_lid_close_on_laptops/

**Comment by irfanhutomo2** [comment]
are u tried this? and success?

**Comment by deonthomasgy** [comment]
@irfanhutomo2 negative, i've been doing research and gathering links before I switch back to Hackintosh, on linux I have the same sleep issue but I am able to work around it by setting the system to hibernate when I close the lid, this works fine for me on linux, however if it works on Mac. I will switch back as that is my only issue.

**Comment by H3C4T0M8** [comment]
Good evening. Please check this page. https://elitemacx86.com/threads/how-to-fix-sleep-wake-on-macos-clover-opencore.955/  will check if we can fix it with deonthomasgy in the next days....we have contact via discord, and we will lock for a way how we can fix the fix the problem with 10210 (don't remember the exactly cpu model that you guys use)

check this please too

Fixing CPU Power Management
For Intel:

To verify you have working CPU Power Management, see the [Fixing Power Management](https://dortania.github.io/OpenCore-Post-Install/universal/pm.html) page.

Also note that incorrect power management data can result in wake issues, so verify that you're using the correct SMBIOS.

A common kernel panic from wake would be:

Sleep Wake failure in EFI

https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#enabling-x86platformplugin
