### ISSUE TITLE
anyone know what APFS user agent?

### ISSUE THREAD

**Issue by irfanhutomo2** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#6]
this is sometime appear in notification and then bluetooth broken 
![image](https://user-images.githubusercontent.com/97343498/185833097-65f139c8-0c53-419b-9f52-d2ba7bce4acf.png)

**Comment by H3C4T0M8** [comment]
https://keith.github.io/xcode-man-pages/APFSUserAgent.8.html

Not sure if it right. What macOS you use at moment?

**Comment by irfanhutomo2** [comment]
monterey, not showing in big sur

**Comment by H3C4T0M8** [comment]
you can open the console.... than try to go to all log windows. PRESS COMMAND + A BUTTON... HOLD THE COMMAND BUTTON and DROP ALL into trash . Than delete the trash and reboot

Let me know if it work.

**Comment by irfanhutomo2** [comment]
where i can find all log windows 
![image](https://user-images.githubusercontent.com/97343498/185908462-e7187d51-8282-4362-ad05-ec3dd6d5872a.png)

**Comment by H3C4T0M8** [comment]
![Bildschirm­foto 2022-08-22 um 15 00 58](https://user-images.githubusercontent.com/96039915/185928410-fdbc4da4-619e-487a-b406-f0b7f23031ef.png)
![Bildschirm­foto 2022-08-22 um 15 00 29](https://user-images.githubusercontent.com/96039915/185928416-26eeaded-f946-4384-8c9a-a17fe0e49fe8.png)

Try so...I can't say exactly what to delete....I have delete all protocols wenn I get problem with windows at startup.
For me it have work on Ventura, Monterey and Big Sur...maybe system logs too. I have delete all logs.

**Comment by irfanhutomo2** [comment]
thanks i try it and report later

**Comment by irfanhutomo2** [comment]
still got the notification and then bluetooth broken, only restart can solve the problem

**Comment by irfanhutomo2** [comment]
trying back to OC 8.0 will report later

**Comment by irfanhutomo2** [comment]
maybe i fix it by add IntelBTPatcher.kext at newer intel bt kext 2.2.0

**Comment by H3C4T0M8** [comment]
I have see this kext some days before.... but don't know what this kext do. Let me know if it really work. Thanks

**Comment by irfanhutomo2** [comment]
i add intelBTPatcher and somehow the APFS dont appear again and bluetooth not broken, but i will report you again if something happen, thanks!

**Comment by irfanhutomo2** [comment]
still have that issue and only happen in monterey, in ventura and big sur no issue with BT

**Comment by H3C4T0M8** [comment]
https://dortania.github.io/builds/?product=IntelBluetoothFirmware&viewall=true
new kexts online...hope it help

**Comment by irfanhutomo2** [comment]
still get same error, back to bigsur again, in ventura notthing happen only in monterey, maybe i upgrade straight to ventura when stable release
