### ISSUE TITLE
Cannot Boot

### ISSUE THREAD

**Issue by ViperK75** [H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore#9]
Hi,

I have been following your work for a while but i have not been able to get the EFI to boot into the install screen. I end up with a blank screen after all the verbose text.

The spec is the same as your machine, with a 4K screen.

**Comment by H3C4T0M8** [comment]
Good morning. I am in Ukraine at moment, so it's not possible to check what's the problem. If you don't like to wait, you can ask in www.osxlatitude.com forum. I am sure this guys can help you.

Thanks
